### ISSUE TITLE
Logs stop pushing

### ISSUE THREAD

**Issue by stefansedich** [dwbutler/logstash-logger#105]
After some time my logs will just stop pushing (writing to logentries over https with the tcp device), in the logs I can see it throwing these:

ERROR -- : [LogStashLogger::Device::TCP] Errno::ETIMEDOUT - Operation timed out

Eventually if I keep pushing logs it might start working again but I do seem to lose the logs during that time, and then after a while stop working again. I am using default confirmation for all of the buffer configuration.

Is there anything obvious I could have missed? I use the le_ruby logger which does something simmilar where it will open the connection and use it until it fails reconnecting and that runs rock solid.

I thought maybe I was losing logs when the connection dies but according to another issue it says that it should handle this gracefully and push when it comes back up, when seeing this loss I am pushing < 50 events so it should not be the case they are dropped on the floor due to the buffer being full.

**Comment by dwbutler** [comment]
If you're getting timeout errors over TCP, I would suspect that your TCP listener (presumably Logstash?) is under too heavy load. What kind of log volume are you pushing into it? If this is over the network, it could also be a network issue.

LogStashLogger will keep log messages in its buffer for a time, but if the output is erroring out long enough, the buffer will get full and messages will get discarded. This is usually desirable behavior to keep your app or program responsive.

I checked the source code for the le gem. It doesn't appear to have any special advantage that would make it more stable. In fact, it doesn't buffer messages so any error would cause message loss. See https://github.com/rapid7/le_ruby/blob/master/lib/le/host/http.rb#L269-L274

**Comment by stefansedich** [comment]
Ok thanks,

I am writing to logentries and we normally push high volumes from our other services, this is a new service and at the moment it is very very low volume.

I will keep digging and open up another issue if I track something down.



Thanks
