### ISSUE TITLE
Issue - initialize logger with certificate file path does not work for ruby 2.4.1

### ISSUE THREAD

**Issue by vuhailuyen1991** [dwbutler/logstash-logger#132]
In order to create a new logger instance i have to: 

`
 cert = OpenSSL::X509::Certificate.new(File.open(ENV['LOG_STASH_CERTIFICATE']))
`
`
ssl_context = OpenSSL::SSL::SSLContext.new.tap do |ctx|
    ctx.set_params(:cert => cert)
  end
`

reference: https://ruby-doc.org/stdlib-2.4.0/libdoc/openssl/rdoc/OpenSSL/SSL/SSLSocket.html

**Comment by dwbutler** [comment]
@vuhailuyen1991 Can you please try the `fix/ssl-cert` branch and let me know if that fixes the issue?

@glaszig Any comments? I'm not sure if the OpenSSL API changed in Ruby 2.4. It doesn't seem like it did.

**Comment by vuhailuyen1991** [comment]
Yes it works

**Comment by glaszig** [comment]
yes, looks like an oversight on my part. ruby openssl docs are somewhat weird as well.
