### ISSUE TITLE
Cancelled events are being logged

### ISSUE THREAD

**Issue by gdeoliveira** [dwbutler/logstash-logger#133]
I would like to be able to cancel (i.e. filter) some events by calling the [LogStash::Event#cancel](http://www.rubydoc.info/gems/logstash-event/1.1.5/LogStash%2FEvent:cancel) method on them (thus setting [LogStash::Event#cancelled?](http://www.rubydoc.info/gems/logstash-event/1.1.5/LogStash%2FEvent:cancelled%3F) to `true`).

Is there a plan for adding this functionality?

**Comment by dwbutler** [comment]
Hi,

I wasn't aware of the event cancelling functionality. I would accept a pull request.

I'm not sure the best way to implement this. Probably by setting `@event` to `nil` in [LogStashLogger::Formatter::Base#call](https://github.com/dwbutler/logstash-logger/blob/a40fbb5b40b297b4ea479078e3463e6580d6ae27/lib/logstash-logger/formatter/base.rb#L18)
