### ISSUE TITLE
Default logging is still in JSON format

### ISSUE THREAD

**Issue by arianf** [dwbutler/logstash-logger#139]
These are my configurations
```
  config.logstash.type = :multi_delegator
  config.logstash.outputs = [
    {
      type: :file,
      path: 'log/default.log',
      formatter: ::Logger::Formatter
    },
    {
      type: :file,
      path: 'log/json.log',
      formatter: :json
    }
  ]
```

Both logs are in json format, how can I change one of them to be the default format before I installed the `logstash-logger` gem?

**Comment by arianf** [comment]
Figured out my issue... `multi_delegator` is supposed to be `multi_logger`

**Comment by dwbutler** [comment]
It would probably make sense to emit a warning if multiple formatters are passed into the MultiDelegator. This would make the configuration problem more obvious.
