### ISSUE TITLE
What's the story for log rotation when using this gem?

### ISSUE THREAD

**Issue by arianf** [dwbutler/logstash-logger#145]
I've previously had to use copytruncate with the regular `Rails.logger`, does using this gem require the use of `copytruncate` when outputting to `file`?

```
/home/rails/myapp/shared/log/production.json {
  daily
  missingok
  rotate 7
  notifempty
  copytruncate # needed by rails to avoid restart
  compress
  delaycompress
}
```

**Comment by dwbutler** [comment]
Yes, that seems right. LogStashLogger writes to a file the same way Rails does.
