### ISSUE TITLE
Not working on production

### ISSUE THREAD

**Issue by mbajur** [dwbutler/logstash-logger#16]
Hello!
I'm trying to use logstash-logger but i have problem with configuring it on production. In developement environment, everything works great but on production, i'm not able to send my logs to logstash server.

My **production.rb** file looks like that:

    Rails.application.configure do
        # Settings specified here will take precedence over those in config/application.rb.

        # Code is not reloaded between requests.
        config.cache_classes = true

        # Eager load code on boot. This eager loads most of Rails and
        # your application in memory, allowing both threaded web servers
        # and those relying on copy on write to perform better.
        # Rake tasks automatically ignore this option for performance.
        config.eager_load = true

        # Full error reports are disabled and caching is turned on.
        config.consider_all_requests_local       = false
        config.action_controller.perform_caching = true

        # Enable Rack::Cache to put a simple HTTP cache in front of your application
        # Add `rack-cache` to your Gemfile before enabling this.
        # For large-scale production use, consider using a caching reverse proxy like nginx, varnish or squid.
        # config.action_dispatch.rack_cache = true

        # Disable Rails's static asset server (Apache or nginx will already do this).
        config.serve_static_assets = false

        # Compress JavaScripts and CSS.
        config.assets.js_compressor = :uglifier
        # config.assets.css_compressor = :sass

        # Do not fallback to assets pipeline if a precompiled asset is missed.
        config.assets.compile = false

        # Generate digests for assets URLs.
        config.assets.digest = true

        # Version of your assets, change this if you want to expire all your assets.
        config.assets.version = '1.0'

        # Specifies the header that your server uses for sending files.
        # config.action_dispatch.x_sendfile_header = "X-Sendfile" # for apache
        # config.action_dispatch.x_sendfile_header = 'X-Accel-Redirect' # for nginx

        # Force all access to the app over SSL, use Strict-Transport-Security, and use secure cookies.
        # config.force_ssl = true

        # Set to :debug to see everything in the log.
        config.log_level = :info

        # Prepend all log lines with the following tags.
        # config.log_tags = [ :subdomain, :uuid ]

        # Use a different logger for distributed setups.
        # config.logger = ActiveSupport::TaggedLogging.new(SyslogLogger.new)

        # Use a different cache store in production.
        # config.cache_store = :mem_cache_store

        # Enable serving of images, stylesheets, and JavaScripts from an asset server.
        # config.action_controller.asset_host = "http://assets.example.com"

        # Precompile additional assets.
        # application.js, application.css, and all non-JS/CSS in app/assets folder are already added.
        # config.assets.precompile += %w( search.js )

        # Ignore bad email addresses and do not raise email delivery errors.
        # Set this to true and configure the email server for immediate delivery to raise delivery errors.
        # config.action_mailer.raise_delivery_errors = false

        # Enable locale fallbacks for I18n (makes lookups for any locale fall back to
        # the I18n.default_locale when a translation cannot be found).
        config.i18n.fallbacks = true

        # Send deprecation notices to registered listeners.
        config.active_support.deprecation = :notify

        # Disable automatic flushing of the log to improve performance.
        # config.autoflush_log = false

        # Use default logging formatter so that PID and timestamp are not suppressed.
        # config.log_formatter = ::Logger::Formatter.new

        # Do not dump schema after migrations.
        config.active_record.dump_schema_after_migration = false

        config.action_mailer.default_url_options = { host: "domain.com" }
        config.action_mailer.asset_host          = "http://domain.com"
        config.action_mailer.delivery_method     = :smtp
        config.action_mailer.smtp_settings = {
          authentication:       :plain,
          address:              ENV["MAILGUN_SMTP_SERVER"],
          user_name:            ENV["MAILGUN_SMTP_LOGIN"],
          password:             ENV["MAILGUN_SMTP_PASSWORD"],
          port:                 ENV["MAILGUN_SMTP_PORT"],
          domain:               "domain.com"
        }

        config.logstasher.enabled = true
        config.logstasher.log_controller_parameters = true
        config.logstasher.suppress_app_log = true

        config.logstash.host = 'domain.com'
        config.logstash.port = 5228
        config.logstash.type = :udp
      end

Have you any idea what can be causing such issue? Any clues or tips where to look for that? Thanks in advance.

**Comment by Shadowssong** [comment]
Sorry to comment on an old issue, but just ran into this same problem.  As @dwbutler suggested, it was another gem that was interfering with logging but only in production.  Specifically for us it was the rails_12factor gem we had configured like this:

```
group :production do
  gem 'rails_12factor'
end
```

Our issue was that we were logging (formatted via lograge), but it was being sent to stdout instead of directly to redis via logstash-logger.  Removing the problem gem resolved the logging problem.

**Comment by dwbutler** [comment]
That certainly explains it. I'll add a note to the readme. @mbajur Can you confirm that this was causing the issue?

**Comment by dwbutler** [comment]
It turns out that Heroku will [inject](https://devcenter.heroku.com/articles/ruby-support#injected-plugins) the `rails_12factor` gem even if you remove it. I'll put a note in the readme about logging gems in general and Heroku in particular.

**Comment by dwbutler** [comment]
I added a new [troubleshooting](https://github.com/dwbutler/logstash-logger#troubleshooting) section to the readme that documents this problem and the solution. Feel free to reopen this issue if it's still not addressed.
