### ISSUE TITLE
Failure when logging non-string objects

### ISSUE THREAD

**Issue by Xylakant** [dwbutler/logstash-logger#23]
When passing an object to any log method that is not a String, a Hash or a Logstash object, the logger errors with 

```
Puma caught this error: undefined method `[]' for nil:NilClass (NoMethodError)
path/to/gems/logstash-logger-0.6.2/lib/logstash-logger/formatter.rb:34:in `build_event'
path/to/gems/logstash-logger-0.6.2/lib/logstash-logger/formatter.rb:12:in `call'
```

The culprit is https://github.com/dwbutler/logstash-logger/blob/master/lib/logstash-logger/formatter.rb#L24 where a default case for anything that is not a String, but can be converted is missing. It would be more robust to test if `data.responds_to :to_s`, so that exception objects or similar can be passed directly.

**Comment by rogierslag** [comment]
Still crashes when it receives an int for example (which can be quite useful for taking averages in kibana)

**Comment by dwbutler** [comment]
@rogierslag I cannot reproduce this. Are you using LogStashLogger >= 0.7?

```ruby
logger = LogStashLogger.new(type: :stdout)
logger.info(1)
{"message":"1","@timestamp":"2015-04-22T07:48:51.934-07:00","@version":"1","severity":"INFO","host":"Davids-MacBook-Pro-2.local"}
```
