### ISSUE TITLE
crashes when invalid UTF-8 is passed

### ISSUE THREAD

**Issue by runa** [dwbutler/logstash-logger#26]
It's not a logstash-logger bug per-se...

See this:

```
[3] pry(main)> LogStashLogger.new(type: :file, path: '/tmp/foo.json').info({"a\xC3" => {"pez" => [ 'gatito' ]}})
JSON::GeneratorError: partial character in source, but hit end
```

I've 'fixed' it by `String#scrub(ing)` the input: 

```ruby
  module LogStashEventExtension
    module Initializer
      def initialize(data={})
        data = _scrub_obj(data)
        super(data)
      end
        
      def _scrub_obj(o)
        ret = o.class.new
        if o.is_a?(Hash)
          o.each{|k, v|
            v = _scrub(v)
            k = _scrub(k)
            ret[k]=v
          }
        else
          o.each.with_index{| v,k|
            v = _scrub(v)
            ret[k]=v
          }
        end
        ret
      end

      def _scrub(v)
          if v.is_a?(String)
            v = v.dup.scrub
          elsif v.respond_to?(:each)
            v = _scrub_obj(v)
          end
          v
      end
    end

    def self.included(klass)
      klass.send :prepend, Initializer
    end
end
```

**Comment by dwbutler** [comment]
What do you think would be reasonable behavior? Print a warning instead of throwing an exception?

**Comment by runa** [comment]
I was not expecting that exception and a 'supposed inoffensive' log stance, throwed an uncatched exception.

Not sure if it's a bug.

thanks for your work :)

**Comment by dwbutler** [comment]
So here's an interesting finding: When I used oj via MultiJson, I could encode the invalid UTF-8 into JSON.

```ruby
 MultiJson.dump({"a\xC3" => {"pez" => [ 'gatito' ]}})
=> "{\"a\xC3\":{\"pez\":[\"gatito\"]}}"
```

Maybe this is an argument in favor of using MultiJson?

**Comment by dwbutler** [comment]
@runa Give the [multi_json](https://github.com/dwbutler/logstash-logger/pull/33) branch a try with Oj. I think this should fix your problem as well as improve performance.

**Comment by dwbutler** [comment]
I opted to not add MultiJson as a dependency, and instead to recommend installing the `oj_mimic_json` gem. This is documented in the new [troubleshooting](https://github.com/dwbutler/logstash-logger#troubleshooting) section in the readme.
