### ISSUE TITLE
LogStashLogger::Device::TCP - Errno::EPIPE - Broken pipe

### ISSUE THREAD

**Issue by kikicarbonell** [dwbutler/logstash-logger#34]
I'm using gem logstash-logger version 0.8.0 in my Rails 4.1 app. My config:
```
    ...
    config.log_level = :info
    config.assets.debug = false

    config.lograge.enabled = true
    config.lograge.formatter = Lograge::Formatters::Logstash.new

    # add time to lograge
    config.lograge.custom_options = lambda do |event|
      {:deploy_name => 'my-app'}
    end

    # Optional, Rails 4 defaults to true in development and false in production
    config.autoflush_log = true

    config.logstash = [
        {
            type: :file,
            path: 'log/staging.log'
        },
        {
            type: :tcp,
            port: ENV['LS_PORT'],
            host: ENV['LS_HOST']
        }
    ]
   ...
```

 When I deploy it all look fine but sometime the error console log shows this messages:
```
LogStashLogger::Device::TCP - Errno::EPIPE - Broken pipe
LogStashLogger::Device::TCP - Errno::EPIPE - Broken pipe
LogStashLogger::Device::TCP - Errno::EPIPE - Broken pipe
LogStashLogger::Device::TCP - Errno::EPIPE - Broken pipe
LogStashLogger::Device::TCP - Errno::EPIPE - Broken pipe
LogStashLogger::Device::TCP - Errno::EPIPE - Broken pipe
```
I suppose that problem is about TCP lost connection or overhead TCP port...I don't know...Anybody have some idea about it?

**Comment by dwbutler** [comment]
It looks to me like LogStashLogger cannot connect to the TCP port that you've configured. (Or that it connects but then immediately disconnects.) You might have a misconfiguration in your environment, or firewall issues. Are you communicating with a local TCP port or a remote port?

**Comment by kikicarbonell** [comment]
@dwbutler thks for your time, but as I say, at the begining of startup app all log was sended to my logstash server, but sometimes the rails app log show:
```
LogStashLogger::Device::TCP - Errno::EPIPE - Broken pipe
```
I haven't a firewall, or any connection restrictions...If I have a connection problem this error should be showed from startup rails app.

**Comment by kikicarbonell** [comment]
@dwbutler do you have any idea?

**Comment by dwbutler** [comment]
It's normal and expected that a TCP connection will sometimes fail. When this happens, the message is most likely lost, and LogStashLogger outputs a warning to STDERR.

I could potentially throw `Stud::Buffer` in there in an attempt to make message delivery more reliable. (i.e. if there is an exception, the message will go back into the in-memory buffer and attempt to be redelivered later.)

**Comment by dwbutler** [comment]
Also note that LogStashLogger will reconnect after a connection failure.

**Comment by kikicarbonell** [comment]
@dwbutler, ok...my main concern is about how avoid a lost of any log. On your previous message you suggest some code change to resend a log and avoid a lost of log, but I'm not clear of how implement it.

**Comment by dwbutler** [comment]
I'll work on it. Hopefully it's as simple as throwing `Stud::Buffer` in there.

**Comment by dwbutler** [comment]
See https://github.com/dwbutler/logstash-logger/pull/35 for progress and further discussion. It's still possible that log messages are dropped, or that duplicate messages are sent when retrying.

**Comment by dwbutler** [comment]
Resolved by #35, released in 0.15.0.

**Comment by sheldonh** [comment]
Was this tested against a TCP Logstash service that disconnects the client for inactivity?

Here is what I observe:

* Initially, events are delivered.
* I stop sending events for a minute.
* The next attempt to send events fails with `Errno::EPIPE`.
* The next attempt after that delivers events, but the the events from the failure are lost.
* Repeat.

We're using `logit.io`, which has a very aggressive client inactivity timeout. For low volume event sources, this pretty much means half of the events are lost.

**Comment by dwbutler** [comment]
@sheldonh In my own testing (locally), when I shut down a TCP server, Ruby's TCP client will initially appear to send messages just fine without raising any exception. Only after a few messages have been sent, will exceptions start being thrown. Could this explain why some of your messages get lost?
