### ISSUE TITLE
Logging to kafka

### ISSUE THREAD

**Issue by felixb** [dwbutler/logstash-logger#37]
Kafka-input/-output is moved into logstash core with upcoming release.
Do you have any plans to implement logging to kafka in the same way logging to redis is available now?

**Comment by dwbutler** [comment]
I wasn't aware of this. I see no reason not to support it. Do you want to take a stab at it?

**Comment by felixb** [comment]
Can do. I'll try to send a PR within a few weeks.

**Comment by dwbutler** [comment]
This has been released in 0.10.0. Thanks again for the contribution!
