### ISSUE TITLE
redis uri is not parsed correctly

### ISSUE THREAD

**Issue by yads** [dwbutler/logstash-logger#41]
When you use the redis uri, such as `:uri => 'redis://localhost:6379/0'` The connection string seems to be parsed as `{:type => 'redis', :host => 'localhost', :port => 6379, :path => '/0'}`. This is then passed to the redis client. Unfortunately I think the redis client is getting confused with the :path parameter since that can specify a unix socket. It almost seems like for redis, you are better off passing the entire uri as the :url option to the redis client. (Note it doesn't matter if you specify the redis db in the uri or not)

FWIW, here's the code we are trying to use:

```
My::Application.configure do
  config.logstash = [{
                         :uri => 'redis://localhost:6379/0'
                     }, {
                         :type => :file
                     }]
end
```

**Comment by dwbutler** [comment]
Fixed in 0.10.1. Thanks for the contribution!
