### ISSUE TITLE
Custom Events can't access tags from Tagged Logging

### ISSUE THREAD

**Issue by platphorm** [dwbutler/logstash-logger#48]
Currently the call to
`LogStashLogger.configuration.customize_event_block.call(event)`
happens before the current_tags are added to the event. As such, when using tagged logging, the customize_event can't access the tags. 

Why do we care?
In my case tagged logging (Rails) is adding a few pieces of information, such as session information, current user etc. In the customize_event call I'd like to change the tags into proper fields.

**Comment by dwbutler** [comment]
Released in 0.10.2
