### ISSUE TITLE
Support syslog as an output 'device'

### ISSUE THREAD

**Issue by timbunce** [dwbutler/logstash-logger#50]
I'd like to use logstash-logger but need to be able to send the JSON logs to the local syslogd (which then forwards to a remote logstash and does local disk-assisted queuing if the remote logstash is down).

**Comment by dwbutler** [comment]
Makes sense. Do you want to try to tackle this?

**Comment by dwbutler** [comment]
For reference, here's the implementation of the Ruby 2.0+ [Syslog::Logger](https://github.com/ruby/ruby/blob/trunk/ext/syslog/lib/syslog/logger.rb).

We wouldn't be able to use this class because `LogStash::Logger` still supports Ruby 1.9. But we can be inspired by it!

**Comment by dwbutler** [comment]
Syslog support released in 0.14.0.

**Comment by dwbutler** [comment]
@timbunce Give it a try and let me know how well it works for you.

**Comment by timbunce** [comment]
Thanks! I'll let you know if I have any problems.
