### ISSUE TITLE
use an http request header value as a custom value

### ISSUE THREAD

**Issue by oystersauce8** [dwbutler/logstash-logger#51]
we are using logstash-logger like this

    config = LogStashLogger.configure do |config|
      config.customize_event do |event|
        event["other_field"] = "some_other_value"
      end
    end

Is there any way to use an HTTP request header in place of "some_other_value" ?
eg.  request.headers["X-LOADBALANCER-SESSIONID"]

**Comment by dwbutler** [comment]
Hi,

The `customize_event` block is not called in the binding context of the caller. The block only has access to the event passed to it.

I would not recommend having this generic bit of configuration rely on the existence of a `request` object in scope. If your logger is called outside of the context of a request (say, in a background process or the rails console), it will crash. Or you'll have to put some guards in place.

My suggestion is that you store the information you need using the [RequestStore](https://github.com/steveklabnik/request_store) Rack middleware. RequestStore is backed by a thread-local variable which is accessible from anywhere.

Here's an example of how you can get it to work (assuming Rails).

In ApplicationController:

```ruby
before_filter :track_load_balancer_session_id

def track_load_balancer_session_id
  RequestStore.store[:load_balancer_session_id] = request.headers["X-LOADBALANCER-SESSIONID"]
end
```

In application.rb:

```ruby
LogStashLogger.configure do |config|
  config.customize_event do |event|
    event["session_id"] = RequestStore[:load_balancer_session_id]
  end
end
```

**Comment by timbunce** [comment]
Hi @dwbutler. Since this is a useful pattern could you add it to the docs?
