### ISSUE TITLE
override default logging to STDOUT/STDERR

### ISSUE THREAD

**Issue by ageetha** [dwbutler/logstash-logger#63]
by default ruby-runtime logs to STDOUT & STDERR . can this be redirected to logstash using logstash-logger without doing any code changes?

**Comment by dwbutler** [comment]
What is `ruby-runtime`? Are you talking about Ruby itself? Can you give some examples of such logging? I suspect that this kind of "logging" is really just using `puts` and `warn`.

**Comment by ageetha** [comment]
I have a sample ruby app deployed. When I run it, it provides logs as follows

Started GET "/" for 75.126.172.171 at 2015-10-26 17:12:32 +0000
Processing by SayController#hello as HTML
Rendered say/hello.html.erb within layouts/application (0.0ms)
Completed 200 OK in 2ms (Views: 1.3ms)

**Comment by dwbutler** [comment]
The logs you are seeing are generated by Rails. I'm guessing you are deployed on Heroku, which sends all log output to STDOUT by default. The Rails logger is highly configurable, even on Heroku. See the documentation on [Rails Configuration](https://github.com/dwbutler/logstash-logger#rails-configuration)

**Comment by ageetha** [comment]
The app is deployed on Bluemix, I tried the Rails configuration except for changing the following line to point to actual logstash URL. that did not work and deployment failed. 

# Optional, use a URI to configure. Useful on Heroku
config.logstash.uri = ENV['LOGSTASH_URI']

by pointing config.logstash.url , would rails send the logs to logstash by default  v/s sending to STDOUT?

**Comment by dwbutler** [comment]
It's possible that you've overridden the LogStashLogger configuration unintentionally. This can happen if you have the `rails_12factor` gem installed.
