### ISSUE TITLE
Version 0.14.0 broke server startup on windows

### ISSUE THREAD

**Issue by djgerhab** [dwbutler/logstash-logger#64]
In Logger.rb, there was a commit that added the module Syslog and forced the logstash.type to be syslog required (at least according to the README.md)

*module Syslog
  autoload :Logger, 'syslog/logger'
end*

*#Required
config.logstash.type = :syslog*

For windows server users, this is a problem since it is not supported natively. When attempting to start up a server, I receive the following error block:

**/Ruby21-x64/lib/ruby/gems/2.1.0/gems/logstash-logger-0.15.1/lib/logstash-logger/logger.rb:5:in `<top (required)>': cannot load such file -- syslog (LoadError)**

If we do want support for logging to syslog, and requiring the module, it needs to be conditionally loaded based on the config, rather than stating that config must be of this type. On the project I'm on, we use config.logstash.type = :file.

And yes, for the record, we do use linux servers, where this isn't an issue... however some of our local environments are on Windows

**Comment by dwbutler** [comment]
Hi,

Sorry, I didn't realize syslog was unavailable on Windows. I think a fair solution would be to wrap the offending code in a block that does `rescue LoadError` and ignores the exception.

**Comment by dwbutler** [comment]
The autoload should probably be replaced with an explicit require only when using the syslog logger.

**Comment by dwbutler** [comment]
Fix released in 0.15.2.

**Comment by djgerhab** [comment]
Thank you, much appreciated
