### ISSUE TITLE
Can i edit @timestamp?

### ISSUE THREAD

**Issue by minhyeok4dev** [dwbutler/logstash-logger#74]
For test in my app, i want this feature.
Thank you for Awesome Gem!

**Comment by dwbutler** [comment]
Hi,

There are several ways to edit the timestamp, but it depends on your use case.

The easiest way is to use `customize_event` to modify the generated `LogStash::Event` and set your own timestamp.

```ruby
config = LogStashLogger.configure do |config|
  config.customize_event do |event|
    event.timestamp = <timestamp>
  end
end
```
If you require a different timestamp on each log message, this may not be possible for you. If you're logging a string or hash, when the log message is turned into a `LogStash::Event`, the event's time is set to the current time.

If you construct your own `LogStash::Event` and pass that to the logger, LogStashLogger will leave the timestamp alone. So if you set your own timestamp, it will be preserved.

For reference, please see [LogStashLogger::Formatter::Base](https://github.com/dwbutler/logstash-logger/blob/84388d191a72a7b27bea9e67ba570eb52d535cd2/lib/logstash-logger/formatter/base.rb).

**Comment by minhyeok4dev** [comment]
Thx!! :D
