### ISSUE TITLE
json_lines for redis.conf?

### ISSUE THREAD

**Issue by keepcosmos** [dwbutler/logstash-logger#76]
> NOTE: Do not use this codec if your source input is line-oriented JSON, for example, redis or file inputs. Rather, use the json codec.
https://www.elastic.co/guide/en/logstash/current/plugins-codecs-json_lines.html

Should I do not use json_lines codec for redis configuration?

**Comment by dwbutler** [comment]
I wasn't aware of this recommendation for Redis. I just tested this using `json_lines` and it worked just fine. However, I was testing with Logstash 1.5 rather than the latest (2.3). Perhaps the old behavior has been deprecated in newer releases.

**Comment by dwbutler** [comment]
It looks like the recommendation changed starting with Logstash 2.0.

https://www.elastic.co/guide/en/logstash/1.5/plugins-codecs-json_lines.html
https://www.elastic.co/guide/en/logstash/2.0/plugins-codecs-json_lines.html

**Comment by dwbutler** [comment]
I'm pretty sure `json_lines` will work for file or Redis inputs. It's just wasted processing since the inputs aren't actually `\n` delimited. I'd be curious to know if you actually have trouble with it.

**Comment by dwbutler** [comment]
I tested Logstash 2.3 with both `json` and `json_line` codes. They worked identically. Nevertheless, I'll update the Redis configuration sample to match their current recommendations.

**Comment by dwbutler** [comment]
Updated the documentation and sample. See https://github.com/dwbutler/logstash-logger/commit/780e4a17ffe2725e7317434aad5a894c636972b3

**Comment by keepcosmos** [comment]
Thanks!
