### ISSUE TITLE
How to Satisfy this activerecord-session_store Silencer Module Requirement?

### ISSUE THREAD

**Issue by DaveCollinsJr** [dwbutler/logstash-logger#79]
Hello,

We are using logstash-logger in Rails 4.2.5 with MRI Ruby 2.2.3p173

We use activerecord-session_store (1.0.0 but saw same issue with previous version), which indicates this in the readme:

> Please note that you will need to manually include the silencer module to your custom logger if you are using a logger other than Logger and Syslog::Logger and their subclasses:
> 
> MyLogger.send :include, ActiveRecord::SessionStore::Extension::LoggerSilencer
> This silencer is being used to silence the logger and not leaking private information into the log, and it is required for security reason.

We configure LogStashLogger like so in /config/enviornments/environment-name.rb:

```ruby
  config.logger = LogStashLogger.new(
  type: :multi_delegator,
  outputs: [
    { type: :file, path: "log/#{Rails.env}.log" },
    { host: ENV["ELK_LOG_HOST"], port: ENV["ELK_LOG_PORT"], ssl_certificate: ENV["ELK_LOG_CERT"]}
  ])
```

We have tried many permutations of the LogStashLogger.send :include command but all of them fail during deployment.  Here are the commands we have tried:

```ruby
LogStashLogger.send :include, ActiveRecord::SessionStore::Extension::LoggerSilencer

config.logger.send :include, ActiveRecord::SessionStore::Extension::LoggerSilencer

Logging.logger.send :include, ActiveRecord::SessionStore::Extension::LoggerSilencer

Rails.logger.send :include, ActiveRecord::SessionStore::Extension::LoggerSilencer
```

The top line (which seems the most correct) gives us this error:
  **Error ID: 2fd1ffbb
  Error details saved to: /tmp/passenger-error-22Gh4T.html
  Message from application: undefined method 'level' for module `LogStashLogger' (NameError)
  /var/app/current/vendor/bundle/ruby/2.2.0/gems/activerecord-session_store-1.0.0/lib/active_record/session_store/extension/logger_silencer.rb:16:in `alias_method'**

Has anyone successfully included ActiveRecord::SessionStore::Extension::LoggerSilencer into LogStashLogger?

**Comment by dwbutler** [comment]
The interesting thing about `LogStashLogger` is that it is a module, not a class. Calling `LogStashLogger.new` does not create an instance of `LogStashLogger`, it simply builds a standard ruby `Logger`, configures it, and returns it. This is why `LogStashLogger.send :include, ActiveRecord::SessionStore::Extension::LoggerSilencer` isn't helping you.

I believe the solution is to use `extend` on your logger instance, rather than `include`. This is the correct way to mix in a module into an instance of an object in Ruby. So either of these should work:

```ruby
config.logger.extend ActiveRecord::SessionStore::Extension::LoggerSilencer
Rails.logger.extend ActiveRecord::SessionStore::Extension::LoggerSilencer
```

**Comment by DaveCollinsJr** [comment]
Thanks so much will give it a try!

**Comment by DaveCollinsJr** [comment]
```ruby
# Manually Including Silencer is required by ActiveRecord::SessionStore
  config.logger.extend ActiveRecord::SessionStore::Extension::LoggerSilencer
```

Worked like a champ!

Thanks again

**Comment by dwbutler** [comment]
Great! Probably worth documenting in the readme.
