### ISSUE TITLE
Too many open files - socket(2)

### ISSUE THREAD

**Issue by collimarco** [dwbutler/logstash-logger#85]
Hello!

Yesterday I switched an application in production to Puma. This morning the application is down and about every second or so this message gets written in the Puma error log:

```
LogStashLogger::Device::UDP - Errno::EMFILE - Too many open files - socket(2) - udp
```

Looks like this gem is leaking opened sockets.

**Comment by collimarco** [comment]
More details from lsof and puma error log: https://gist.github.com/collimarco/adcb2ec45d86c37a20560b942b3058bb

**Comment by collimarco** [comment]
The error is likely caused by this gem because removing it has solved the problem and Puma is working (not leaking sockets anymore).

I suppose that [this raise](https://github.com/dwbutler/logstash-logger/blob/7bf99bc5d1205f24b1ae9f5f874a3dad6e3486a7/lib/logstash-logger/device/base.rb#L28) propagates up to the web server and causes its continuous restarts (thus producing the same error again and again until you reach the socket limit).

**Comment by dwbutler** [comment]
On further inspection, there seem to be an equal number of UDP connections and Puma sockets open. This seems to suggest that Puma threads are keeping UDP connections open.

**Comment by dwbutler** [comment]
Based on the error messages I see generated by LogStashLogger, this looks like the format produced by 0.15.x. Leaking connections was fixed in #84 and released in 0.16.0. See also #78 and #67.

**Comment by collimarco** [comment]
Thank you for the support! Yes it can be that: I was using v. 0.15.2.

I'm pretty scared to run into the problem again :) Can you explain me what was going on? For my understanding the exception EMSGSIZE was propagating up to Puma leaking a connection. But **that doesn't explain why Puma was also leaking its connections**  (i.e. puma.sock). https://github.com/puma/puma/issues/1026

> is it communicating with a proxy server such as nginx? 

Yes

**Comment by dwbutler** [comment]
What happened is that when encountering an exception, LogStashLogger would retry forever. But the error is unrecoverable and will never succeed, so the Puma thread gets stuck forever. Compounding the problem, every time a retry happens, the UDP connection was thrown away and a new one was established. But the old connection was not actually closed.

0.16.0 fixes both problems - unrecoverable errors such as this are not retried. And when a connection error happens, the old connection is closed before being thrown away.

**Comment by collimarco** [comment]
I still don't understand why Puma was creating so many `puma.sock` - the two issues are strictly related.

If the thread was simply stuck (the gem was raising and catching exceptions by itself) Puma would have created at most other 16 threads
